# Generated by Django 3.2.6 on 2021-08-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pendente', max_length=12)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
